print("This is my friends birthdays!")
Alice = ("March 15")
Bob = ("July 22")
Charlie = ("November 3")
Louie = ("January 10")
Theo = ("August 30")
print(f"Alice: {Alice}")
print(f"Bob: {Bob}")
print(f"Charlie: {Charlie}")
print(f"Louie: {Louie}")
print(f"Theo: {Theo}")